binary_sensor:
  - platform: mqtt
    name: "Umidade do Solo"
    state_topic: "homeassistant/binary_sensor/umidade_solo/state"
    payload_on: "0"
    payload_off: "1"
    device_class: moisture
    unique_id: umidade_solo_digital

